### ISSUE TITLE
product_template_replenish_cost - Bug in product.product form views

### ISSUE THREAD

**Issue by jjbreard2** [efatto/e-efatto#1]
Hi Sergio

The field managed_replenished_cost should be visible if variant count are greater or equal than 2. 
https://github.com/sergiocorato/e-efatto/blob/12.0/product_template_replenishment_cost/views/product_product.xml

The logic you have implemented is the same than on product.template. Currently, when a product.template has more than one variant, the field is not visible.

**Comment by sergiocorato** [comment]
Hi @jjbreard2, your comment is surely correct, this module is used only on an instance without variant management :)
Sorry to not reply earlier, I didn't notice this issue :)

**Comment by sergiocorato** [comment]
Perhaps it's more appropriate this attrs: https://github.com/OCA/OCB/blob/2892c87f68c2345cff0fffdff43c25445cf1f5ff/addons/product/views/product_views.xml#L54
What do you think?

**Comment by jjbreard2** [comment]
Hi @sergiocorato 

I am actually not a developper, I just can read simple code :) The targeted behavior is the same as on the filed standard_price, so you are right, it will definitely be ok.

In the official odoo addons, there is the line  https://github.com/odoo/odoo/blob/12.0/addons/product/views/product_views.xml#L54

Looks the same too me. 

Thank you for your help !

**Comment by sergiocorato** [comment]
I've pushed the fix, would you try it?
Thanks!

**Comment by jjbreard2** [comment]
Thank you @sergiocorato ! 

Yes we will try it. We'll get back to you ASAP.

**Comment by jjbreard2** [comment]
@sergiocorato

**Comment by jjbreard2** [comment]
We tested it. It's all good ! Thank you for the fix. 

Have a nice day !

Julien
